# Generated by Django 4.1.7 on 2023-03-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("recipes", "0002_initial")]

    operations = [
        migrations.RenameModel(old_name="RecipeIngregient", new_name="RecipeIngredient")
    ]
