# Generated by Django 4.1.7 on 2023-03-31 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("recipes", "0004_alter_favorite_recipe_alter_shoppingcart_recipe")]

    operations = [
        migrations.AlterModelOptions(name="ingredient", options={"ordering": ["-id"]}),
        migrations.AlterModelOptions(
            name="recipe", options={"ordering": ["-pub_date"]}
        ),
        migrations.AlterModelOptions(name="tag", options={"ordering": ["-id"]}),
    ]
