# Generated by Django 4.1.7 on 2023-04-02 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("recipes", "0006_alter_recipeingredient_ingredient_and_more")]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Нужное количество ингредиента для рецепта",
            ),
        )
    ]
