# Generated by Django 4.1.7 on 2023-04-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("recipes", "0007_alter_recipeingredient_amount")]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                upload_to="media/recipe_images/", verbose_name="Картинка"
            ),
        )
    ]
