# Generated by Django 4.1.7 on 2023-04-02 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("recipes", "0008_alter_recipe_image")]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                related_name="recipes", to="recipes.tag", verbose_name="Теги"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^[-a-zA-Z0-9_]+$")
                ],
                verbose_name="Slug тега",
            ),
        ),
    ]
