# Generated by Django 4.1.7 on 2023-04-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("recipes", "0010_alter_recipe_image")]

    operations = [
        migrations.AlterModelOptions(name="ingredient", options={"ordering": ["id"]}),
        migrations.AlterModelOptions(name="tag", options={"ordering": ["id"]}),
    ]
