# Generated by Django 4.1.7 on 2023-03-29 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0002_alter_user_password")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^[\\w.@+-]+$")
                ],
                verbose_name="Имя пользователя",
            ),
        )
    ]
