# Generated by Django 4.1.7 on 2023-04-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0004_alter_follow_options_alter_user_options")]

    operations = [
        migrations.AlterModelOptions(name="user", options={"ordering": ["id"]})
    ]
